### ISSUE TITLE
Is the graphql package supossed to do code formatting?

### ISSUE THREAD

**Issue by ivnnv** [stefanpenner/eslint-ast#53]
Hi,
I have successfully (somehow) working the `eslint-plugin-graphql` on my project, it warms be about deprecated stuff and non-existing queries/mutation against the schema.graphql, thats very nice.

But it is not warning be about nice-to-have code style for example:
```
someQuery() {
  entity{
    value
  }
}
```

should ideally warn me be about NOT having an space between `entity` and the opening brace `{`

so the "correct" format should look like:
```
someQuery() {
  entity {
    value
  }
}
```

Isn't this possible at all? can the actual plugin catch those or should(could) a custom rule be created?

**Comment by hjdivad** [comment]
@ivnnv This project is mainly about giving a framework for writing eslint rules against graphql files, although it does also ship the default graphql validations as eslint rules.

This plugin *could* lint against formatting, but I don't think it makes sense to do so since https://github.com/prettier/eslint-plugin-prettier has GraphQL support.

That said, I think it's even better to have prettier auto-format your file on write.

**Comment by ivnnv** [comment]
Thanks for the clarification, but not everybody uses prettier (I dont).
I have EsLint itself (extending airbnbs+standard configs) indentifying the problems and fixing the files and it does a very job really.

Anyway thanks for poiting that prettier thing out because maybe I can create a specific `lint:gql` to run against only the `.graphql` files using that prettier plugin, which is pretty similar to what Im doing right now to make this work because the example override conflicts when using it whitin my owns `.eslintrc.js` file (id probably open another ticket for that alone).

**Comment by hjdivad** [comment]
> Anyway thanks for poiting that prettier thing out because maybe I can create a specific lint:gql to run against only the .graphql files using that prettier plugin, which is pretty similar to what Im doing right now to make this work 

Yep. Although if you wanted to write a formatting lint rule that uses `@eslint-ast/graphql` that shouldn't be too difficult. I think the general strategy would be similar to what the prettier rule does -- run the formatter and see if there's a difference between the source and the formatted version.

> because the example override conflicts when using it whitin my owns .eslintrc.js file (id probably open another ticket for that alone).

Can you say more about this?

**Comment by ivnnv** [comment]
Sure, this is my simplified regular `.eslintrc.js` file:

```
module.exports = {
    parser: '@typescript-eslint/parser',
    extends: [
        'airbnb-typescript',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking',
        'plugin:react-hooks/recommended'
    ]
}
```

If I try to add an `overrides` key on it like this (instead taking the independent file path):
```
    overrides: [
        {
            files: ['**/*.gql', '**/*.graphql'],
            parser: '@eslint-ast/eslint-plugin-graphql/parser',
            parserOptions: {
                project: `${__dirname}/tsconfig.json`,
                schema: `${__dirname}/schema.gql`,
                ecmaVersion: 11,
            },
            plugins: ['@eslint-ast/eslint-plugin-graphql'],
            extends: require.resolve('@eslint-ast/eslint-plugin-graphql/recommended.js'),
        }
    ],
```

and try to run `lint:gql` (`eslint -c .eslintrc.js --ext .gql,.graphql src/apollo`) I get this error:

```
Error: Error while loading rule '@typescript-eslint/await-thenable':
You have used a rule which requires parserServices to be generated.
You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.

Occurred while linting /Users/xxx/project-yyy/src/apollo/mutations/create-user.gql
```

**Comment by ivnnv** [comment]
friendly ping in case this got buried by other notifications 😬

**Comment by hjdivad** [comment]
@ivnnv The issue is you're still running typescript lint rules on your graphql files, and they rely on a different parser. You can't really mix parser options for multiple parsers like you're doing here.

The way to avoid this sort of thing is to make sure you only specify configurations that require `parser` (and especially `parserOptions`) within `overrides` rather than as the default.


So something like

```js
// .eslintrc.js
module.exports = {
  overrides: [
    {
      files: ['**/*.ts', '**/*.d.ts'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
          project: `${__dirname}/tsconfig.json`,
          ecmaVersion: 11,
      },
      extends: [
        'airbnb-typescript',
        'plugin:@typescript-eslint/recommended',
        // ...
      ]
    },
    {
      files: ['**/*.gql', '**/*.graphql'],
      parser: '@eslint-ast/eslint-plugin-graphql/parser',
      parserOptions: {
          schema: `${__dirname}/schema.gql`,
      },
      plugins: ['@eslint-ast/eslint-plugin-graphql'],
      extends: require.resolve('@eslint-ast/eslint-plugin-graphql/recommended.js'),
    }
  ]
};
```

**Comment by ivnnv** [comment]
Hi, I have tested this approach and it works!, just one file and ready to go.
Thanks for helping :)
